
"use client";

import * as React from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { StickyNote, Download } from "lucide-react";
import jsPDF from "jspdf";

interface NoteDisplayProps {
  notes: string;
  videoTitle?: string; // Optional: for PDF filename
}

export function NoteDisplay({ notes, videoTitle = "EduTube Notes" }: NoteDisplayProps) {

  const handleDownloadPdf = () => {
    const doc = new jsPDF();
    
    // Set metadata
    doc.setProperties({
      title: `${videoTitle} - Notes`,
      subject: 'Video Notes generated by EduTube AI',
      author: 'EduTube AI',
    });

    // Add title to PDF
    doc.setFontSize(18);
    doc.text(`${videoTitle} - Notes`, 14, 22);

    // Add notes content
    doc.setFontSize(11);
    // The 'splitTextToSize' method helps with auto-wrapping text.
    // We'll use a margin of 14 on left/right, so content width is 210 - 14 - 14 = 182.
    const splitNotes = doc.splitTextToSize(notes, 182); 
    let yPosition = 30;
    const pageHeight = doc.internal.pageSize.height;
    const bottomMargin = 20;

    splitNotes.forEach((line: string) => {
      if (yPosition > pageHeight - bottomMargin) {
        doc.addPage();
        yPosition = 22; // Reset Y for new page (after title space if we add titles to each page)
         // Optionally add title to subsequent pages
        doc.setFontSize(18);
        doc.text(`${videoTitle} - Notes (cont.)`, 14, yPosition);
        yPosition += 8;
        doc.setFontSize(11);
      }
      doc.text(line, 14, yPosition);
      yPosition += 7; // Adjust line height as needed
    });
    
    // Sanitize filename
    const safeVideoTitle = videoTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    doc.save(`${safeVideoTitle}_notes.pdf`);
  };

  return (
    <Card className="mt-8 shadow-lg">
      <CardHeader>
        <div className="flex justify-between items-start">
          <div>
            <CardTitle className="flex items-center text-2xl">
              <StickyNote className="mr-2 h-6 w-6 text-primary" />
              Revision Notes
            </CardTitle>
            <CardDescription>Key points structured for easy revision.</CardDescription>
          </div>
          <Button onClick={handleDownloadPdf} variant="outline" size="sm">
            <Download className="mr-2 h-4 w-4" />
            Download PDF
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <ScrollArea className="h-72 w-full rounded-md border p-4">
          <pre className="whitespace-pre-wrap text-sm leading-relaxed font-sans">{notes}</pre>
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
